version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=main
    volumes:
      - postgres_data:/bitnami/postgresql
  # app:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   container_name: nest-docker-postgres
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/app
  #     - /usr/app/node_modules

volumes:
  postgres_data:
